version: '3'
services:
  cerebro:
    image: lmenezes/cerebro:0.8.3
    container_name: cerebro
    ports:
      - "9000:9000"
    command:
      - -Dhosts.0.host=http://elasticsearch:9200
    networks:
      - elknet
#  elasticsearch:
#    image: elasticsearch:7.1.0
#    container_name: elasticsearch
#    environment:
#      - "cluster.name=elasticsearch" #设置集群名称为elasticsearch
#      - "discovery.type=single-node" #以单一节点模式启动
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" #设置使用jvm内存大小
#    volumes:
#      - ./ELKConfig/elasticsearch/plugins:/usr/share/elasticsearch/plugins #插件文件挂载
#      - ./ELKConfig/elasticsearch/data:/usr/share/elasticsearch/data #数据文件挂载
#    ports:
#      - 9200:9200
#      - 9300:9300
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.0
    container_name: elasticsearch1
    environment:
      - cluster.name=elk
      - node.name=elasticsearch1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.seed_hosts=elasticsearch1,elasticsearch2
      - cluster.initial_master_nodes=elasticsearch1,elasticsearch2
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./ELKConfig/elasticsearch/data1:/usr/share/elasticsearch/data #数据文件挂载
      - ./ELKConfig/elasticsearch/plugins:/usr/share/elasticsearch/plugins #插件文件挂载
    ports:
      - 9200:9200
    networks:
      - elknet
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.0
    container_name: elasticsearch2
    environment:
      - cluster.name=elk
      - node.name=elasticsearch2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.seed_hosts=elasticsearch1,elasticsearch2
      - cluster.initial_master_nodes=elasticsearch1,elasticsearch2
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./ELKConfig/elasticsearch/data2:/usr/share/elasticsearch/data #数据文件挂载
      - ./ELKConfig/elasticsearch/plugins:/usr/share/elasticsearch/plugins #插件文件挂载
    networks:
      - elknet
  kibana:
    image: kibana:7.1.0
    container_name: kibana
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    environment:
      - I18N_LOCALE=zh-CN
      - XPACK_GRAPH_ENABLED=true
      - TIMELION_ENABLED=true
      - XPACK_MONITORING_COLLECTION_ENABLED="true"
    ports:
      - 5601:5601
    networks:
      - elknet
  logstash:
    image: logstash:7.1.0
    container_name: logstash
    volumes:
      - ./ELKConfig/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf #挂载logstash的配置文件
      - ./ELKConfig/logstash/movies.csv:/usr/share/logstash/data/movies.csv #挂载logstash的数据文件
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    networks:
      - elknet
    ports:
      - 4560:4560
  # 配置采集服务
  skywalking-oap:
    image: apache/skywalking-oap-server:8.7.0-es6
    container_name: skywalking-oap
    restart: always
    depends_on:
      - elasticsearch
    ports:
      - 8008:11800
      #- 8009:12800
    environment:
      TZ: Asia/Shanghai
      SW_STORAGE: elasticsearch
      SW_STORAGE_ES_CLUSTER_NODES: elasticsearch:9200
    networks:
      - elknet
  # 配置后台管理界面
  skywalking-ui:
    image: apache/skywalking-ui:8.7.0
    container_name: skywalking-ui
    depends_on:
      - skywalking-oap
    restart: always
    ports:
      - 8010:8080
    environment:
      SW_OAP_ADDRESS: http://skywalking-oap:12800
      SW_TIMEOUT: 20000
    networks:
      - elknet
networks:
  elknet:
    driver: bridge